[global]

    workgroup = WORKGROUP
    server string = Secure Hardened SMB Server (%h)


    interfaces = 127.0.0.1 192.168.1.0/24
    bind interfaces only = yes

    log level = 3
    log file = /var/log/samba/log.%m
    max log size = 50000
    logging = file
    panic action = /usr/share/samba/panic-action %d

    server min protocol = SMB2_10
    server max protocol = SMB3
    
    server signing = mandatory
    
    server smb encrypt = mandatory

    server role = standalone server
    obey pam restrictions = yes
    security = user
    
    map to guest = Never
    guest account = nobody
    usershare allow guests = no

    restrict anonymous = 2

    unix password sync = yes
    passwd program = /usr/bin/passwd %u
    passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
    pam password change = yes

    wins support = no
    wins proxy = no

    unix extensions = no
    wide links = no
    follow symlinks = yes

    vfs objects = acl_xattr

[PublicShare]
    comment = Hardened Share for SIEM Demonstration
    path = /home/vsftpd/smb_share
    browsable = yes
    writable = yes
    read only = no
    
    valid users = vsftpd
    guest ok = no
    
    force create mode = 0660
    force directory mode = 0770
