listen=YES
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
connect_from_port_20=YES

# Для демонстрации всех атак
chroot_local_user=YES
allow_writeable_chroot=YES
secure_chroot_dir=/var/run/vsftpd/empty

pam_service_name=vsftpd
ssl_enable=NO                       # ← обязательно для MITM
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

# Лимиты — удобно для демонстрации DoS
max_clients=8
max_per_ip=3
max_login_fails=3

# Максимально подробное логирование
syslog_enable=NO
dual_log_enable=YES
log_ftp_protocol=YES
vsftpd_log_file=/var/log/vsftpd.log
xferlog_enable=YES
xferlog_std_format=YES
xferlog_file=/var/log/xferlog

pasv_enable=YES
pasv_min_port=10000
pasv_max_port=10100