Timeout 60
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5

<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    Alias /dav /var/www/webdav

    <Directory /var/www/webdav>
        DAV On
        
        Options -Indexes +FollowSymLinks
        AllowOverride None

        AuthType Basic
        AuthName "Secure WebDAV Access"
        AuthUserFile /etc/apache2/webdav.password
        
        Require valid-user
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/webdav_error.log
    CustomLog ${APACHE_LOG_DIR}/webdav_access.log combined
</VirtualHost>
